In [ ]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt
import pydotplus
from sklearn import tree, metrics, model_selection, preprocessing
from IPython.display import Image, display
import seaborn as sns
%matplotlib inline

In [ ]:
from google.colab import files
files.upload()

Saving update.csv to update.csv


{'update.csv': b'Gender,Age,City,CGPA,Program,Residence Type,Academic Pressure,Does the end of the semester affect sense of the academic pressure?,How often you feel Academic Pressure in a running semester?,Are you satisfied with your results each semester?,How much academic help do you get from your friends?,Did you receive a waiver or scholarship at your university?,How does the lack of financial aid affect your academic performance?,Chronic_Illness,Sleep Duration(hours),Sleep Quality,Financial Stress,Have you ever had suicidal thoughts ?,Overall Student mental Health\r\nMale,20,Gazipur,3.6,CSE,In campus,Medium,No,Never,Yes,Always,Yes,Slightly,No,5,Poor,No,No,Good\r\nFemale,20,Gazipur,2.77,CSE,In campus,High,No,Always,No,Never,No,Slightly,No,5,Poor,Yes,No,Bad\r\nMale,19,Dhaka,3.31,Architecture,In campus,Low,Yes,Always,No,Sometimes,Yes,Moderately,Yes,5,Average,No,No,Medium\r\nFemale,19,Jessore,2.78,BBA,In campus,High,No,Sometimes,No,Sometimes,No,Slightly,No,5,Average,No,No,Medium\r\nF

In [ ]:
df = pd.read_csv('update.csv')

In [ ]:
df

Gender  Age     City  CGPA       Program Residence Type  \
0       Male   20  Gazipur  3.60           CSE      In campus   
1     Female   20  Gazipur  2.77           CSE      In campus   
2       Male   19    Dhaka  3.31  Architecture      In campus   
3     Female   19  Jessore  2.78           BBA      In campus   
4     Female   20   Khulna  3.21           CSE    With Family   
...      ...  ...      ...   ...           ...            ...   
1053  Female   21  Rangpur  3.36       English    With Family   
1054    Male   22   Khulna  3.80      Pharmacy      In campus   
1055  Female   21  Barisal  3.80           BBA      In campus   
1056    Male   22   Sylhet  3.60     Economics      In campus   
1057  Female   22  Comilla  3.80     Pharmacy     With Family   

     Academic Pressure  \
0               Medium   
1                 High   
2                  Low   
3                 High   
4                 High   
...                ...   
1053              High   
1054              High   
1055               Low   
1056              High   
1057              High   

     Does the end of the semester affect sense of the academic pressure?  \
0                                                    No                    
1                                                    No                    
2                                                   Yes                    
3                                                    No                    
4                                                   Yes                    
...                                                 ...                    
1053                                                 No                    
1054                                                 No                    
1055                                                 No                    
1056                                                Yes                    
1057                                                 No                    

     How often you feel Academic Pressure in a running semester?  \
0                                                 Never            
1                                                Always            
2                                                Always            
3                                             Sometimes            
4                                             Sometimes            
...                                                 ...            
1053                                          Sometimes            
1054                                             Always            
1055                                              Never            
1056                                          Sometimes            
1057                                              Never            

     Are you satisfied with your results each semester?  \
0                                                   Yes   
1                                                    No   
2                                                    No   
3                                                    No   
4                                                    No   
...                                                 ...   
1053                                                Yes   
1054                                                Yes   
1055                                                Yes   
1056                                                Yes   
1057                                                Yes   

     How much academic help do you get from your friends?  \
0                                                Always     
1                                                 Never     
2                                             Sometimes     
3                                             Sometimes     
4                                                 Never     
...                                                 ...     
1053                                          

In [ ]:
df['Overall Student mental Health'].value_counts()

Overall Student mental Health
Medium    424
Good      359
Bad       275
Name: count, dtype: int64

In [ ]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()

In [ ]:
df['Gender']=label_encoder.fit_transform(df['Gender'])
df['Gender'].unique()

array([1, 0])

In [ ]:
df['Age']=label_encoder.fit_transform(df['Age'])
df['Age'].unique()

array([1, 0, 3, 2, 5, 4, 6, 7])

In [ ]:
df['City']=label_encoder.fit_transform(df['City'])
df['City'].unique()

array([ 4,  3,  5,  6,  8,  9, 11, 10,  0,  1,  2, 12,  7])

In [ ]:
df['CGPA']=label_encoder.fit_transform(df['CGPA'])
df['CGPA'].unique()

array([71, 23, 57, 24, 49, 51, 64, 26, 10, 17, 13, 40, 21, 89, 86, 34, 45,
       14, 33, 16, 29, 77, 83, 82, 78, 38,  6, 79, 56, 74, 84, 81,  4, 63,
       48,  5, 65,  2,  7, 47, 91, 42, 18, 43, 72,  9, 69, 62, 75, 25, 61,
       32, 37, 15, 39, 19, 20, 12, 54, 41, 22, 35,  8, 36, 80, 52, 30, 68,
       70, 88, 55,  3, 31, 50, 67, 85, 53, 87, 44, 46,  1, 11,  0, 60, 66,
       58, 76, 28, 90, 59, 73, 27])

In [ ]:
df['Program']=label_encoder.fit_transform(df['Program'])
df['Program'].unique()

array([ 5,  1,  3, 16,  6, 18, 21,  0, 10,  4, 25, 14,  9,  8, 12, 24, 11,
       23, 22, 20, 15,  2,  7, 19, 13, 26, 17])

In [ ]:
df['Residence Type']=label_encoder.fit_transform(df['Residence Type'])
df['Residence Type'].unique()

array([1, 2, 0])

In [ ]:
df['Academic Pressure']=label_encoder.fit_transform(df['Academic Pressure'])
df['Academic Pressure'].unique()

array([2, 0, 1])

In [ ]:
df['Does the end of the semester affect sense of the academic pressure?']=label_encoder.fit_transform(df['Does the end of the semester affect sense of the academic pressure?'])
df['Does the end of the semester affect sense of the academic pressure?'].unique()

array([0, 1])

In [ ]:
df['How often you feel Academic Pressure in a running semester?']=label_encoder.fit_transform(df['How often you feel Academic Pressure in a running semester?'])
df['How often you feel Academic Pressure in a running semester?'].unique()

array([1, 0, 2])

In [ ]:
df['Are you satisfied with your results each semester?']=label_encoder.fit_transform(df['Are you satisfied with your results each semester?'])
df['Are you satisfied with your results each semester?'].unique()

array([2, 1, 0])

In [ ]:
df['How much academic help do you get from your friends?']=label_encoder.fit_transform(df['How much academic help do you get from your friends?'])
df['How much academic help do you get from your friends?'].unique()

array([0, 1, 2])

In [ ]:
df['Did you receive a waiver or scholarship at your university?']=label_encoder.fit_transform(df['Did you receive a waiver or scholarship at your university?'])
df['Did you receive a waiver or scholarship at your university?'].unique()

array([1, 0])

In [ ]:
df['How does the lack of financial aid affect your academic performance?']=label_encoder.fit_transform(df['How does the lack of financial aid affect your academic performance?'])
df['How does the lack of financial aid affect your academic performance?'].unique()

array([2, 0, 1])

In [ ]:
df['Chronic_Illness']=label_encoder.fit_transform(df['Chronic_Illness'])
df['Chronic_Illness'].unique()

array([0, 1])

In [ ]:
df['Sleep Duration(hours)']=label_encoder.fit_transform(df['Sleep Duration(hours)'])
df['Sleep Duration(hours)'].unique()

array([3, 6, 4, 5, 2, 1, 0])

In [ ]:
df['Sleep Quality']=label_encoder.fit_transform(df['Sleep Quality'])
df['Sleep Quality'].unique()

array([2, 0, 1, 3])

In [ ]:
df['Financial Stress']=label_encoder.fit_transform(df['Financial Stress'])
df['Financial Stress'].unique()

array([0, 1])

In [ ]:
df['Have you ever had suicidal thoughts ?']=label_encoder.fit_transform(df['Have you ever had suicidal thoughts ?'])
df['Have you ever had suicidal thoughts ?'].unique()

array([0, 1])

In [ ]:
df['Overall Student mental Health']=label_encoder.fit_transform(df['Overall Student mental Health'])
df['Overall Student mental Health'].unique()

array([1, 0, 2])

In [ ]:
df.describe()

Gender          Age         City         CGPA      Program  \
count  1058.000000  1058.000000  1058.000000  1058.000000  1058.000000   
mean      0.498110     3.165406     5.570888    47.702268    10.826087   
std       0.500233     2.198317     3.628071    27.408491     7.300030   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     1.000000     3.000000    22.000000     5.000000   
50%       0.000000     3.000000     5.500000    48.000000    10.000000   
75%       1.000000     5.000000     9.000000    71.000000    16.000000   
max       1.000000     7.000000    12.000000    91.000000    26.000000   

       Residence Type  Academic Pressure  \
count     1058.000000        1058.000000   
mean         1.432892           0.915879   
std          0.556832           0.833041   
min          0.000000           0.000000   
25%          1.000000           0.000000   
50%          1.000000           1.000000   
75%          2.000000           2.000000   
max          2.000000           2.000000   

       Does the end of the semester affect sense of the academic pressure?  \
count                                        1058.000000                     
mean                                            0.448960                     
std                                             0.497623                     
min                                             0.000000                     
25%                                             0.000000                     
50%                                             0.000000                     
75%                                             1.000000                     
max                                             1.000000                     

       How often you feel Academic Pressure in a running semester?  \
count                                        1058.000000             
mean                                            1.003781             
std                                             0.879701             
min                                             0.000000             
25%                                             0.000000             
50%                                             1.000000             
75%                                             2.000000             
max                                             2.000000             

       Are you satisfied with your results each semester?  \
count                                        1058.000000    
mean                                            1.482042    
std                                             0.522130    
min                                             0.000000    
25%                                             1.000000    
50%                                             1.000000    
75%                                             2.000000    
max                                             2.000000    

       How much academic help do you get from your friends?  \
count                                        1058.000000      
mean                                            1.089792      
std                                             0.850438      
min                                             0.000000      
25%                                             0.000000      
50%                                             1.000000      
75%                                             2.000000      
max                                             2.000000      

       Did you receive a waiver or scholarship at your university?  \
count                                        1058.000000             
mean                                            0.523629             
std                                             0.499678             
min                                             0.000000             
25%                                             0.000000             
50%                                             1.000000             
75%   

In [ ]:
df.corr()

Gender       Age  \
Gender                                              1.000000 -0.025955   
Age                                                -0.025955  1.000000   
City                                                0.026138  0.038088   
CGPA                                               -0.032645  0.053560   
Program                                            -0.015894  0.072126   
Residence Type                                     -0.081971 -0.046184   
Academic Pressure                                  -0.069627  0.031886   
Does the end of the semester affect sense of th...  0.031917 -0.099947   
How often you feel Academic Pressure in a runni...  0.004316 -0.048756   
Are you satisfied with your results each semester? -0.032730  0.040918   
How much academic help do you get from your fri...  0.017078 -0.041351   
Did you receive a waiver or scholarship at your...  0.072093 -0.036721   
How does the lack of financial aid affect your ...  0.023283  0.058427   
Chronic_Illness                                    -0.082513  0.022533   
Sleep Duration(hours)                               0.035488  0.019526   
Sleep Quality                                       0.077923 -0.056725   
Financial Stress                                   -0.000527 -0.072466   
Have you ever had suicidal thoughts ?               0.019496 -0.094581   
Overall Student mental Health                      -0.094972  0.128078   

                                                        City      CGPA  \
Gender                                              0.026138 -0.032645   
Age                                                 0.038088  0.053560   
City                                                1.000000 -0.031217   
CGPA                                               -0.031217  1.000000   
Program                                             0.017612 -0.065790   
Residence Type                                     -0.003497  0.010251   
Academic Pressure                                  -0.040753  0.310373   
Does the end of the semester affect sense of th... -0.025243 -0.013427   
How often you feel Academic Pressure in a runni... -0.016091  0.207575   
Are you satisfied with your results each semester? -0.033039  0.339592   
How much academic help do you get from your fri... -0.086847 -0.059572   
Did you receive a waiver or scholarship at your... -0.005883  0.157360   
How does the lack of financial aid affect your ... -0.021593  0.138073   
Chronic_Illness                                    -0.045752 -0.013113   
Sleep Duration(hours)                               0.033631  0.284842   
Sleep Quality                                      -0.065325 -0.150202   
Financial Stress                                    0.027197 -0.163042   
Have you ever had suicidal thoughts ?               0.042586 -0.274264   
Overall Student mental Health                       0.017887  0.391432   

                                                     Program  Residence Type  \
Gender                                             -0.015894       -0.081971   
Age                                                 0.072126       -0.046184   
City                                                0.017612       -0.003497   
CGPA                                               -0.065790        0.010251   
Program                                             1.000000        0.015978   
Residence Type                                      0.015978        1.000000   
Academic Pressure                                  -0.055458        0.074499   
Does the end of the semester affect sense of th... -0.002967        0.014942   
How often you feel Academic Pressure in a runni...  0.007911        0.044940   
Are you satisfied with your results each semester?  0.001414        0.046289   
How much academic help do you get from your fri... -0.008302        0.057688   
Did you receive a waiver or scholarship at your... -0.039074       -0.033398   
How does the lack of financial aid affect your ...  

In [ ]:
df.head()

Gender  Age  City  CGPA  Program  Residence Type  Academic Pressure  \
0       1    1     4    71        5               1                  2   
1       0    1     4    23        5               1                  0   
2       1    0     3    57        1               1                  1   
3       0    0     5    24        3               1                  0   
4       0    1     6    49        5               2                  0   

   Does the end of the semester affect sense of the academic pressure?  \
0                                                  0                     
1                                                  0                     
2                                                  1                     
3                                                  0                     
4                                                  1                     

   How often you feel Academic Pressure in a running semester?  \
0                                                  1             
1                                                  0             
2                                                  0             
3                                                  2             
4                                                  2             

   Are you satisfied with your results each semester?  \
0                                                  2    
1                                                  1    
2                                                  1    
3                                                  1    
4                                                  1    

   How much academic help do you get from your friends?  \
0                                                  0      
1                                                  1      
2                                                  2      
3                                                  2      
4                                                  1      

   Did you receive a waiver or scholarship at your university?  \
0                                                  1             
1                                                  0             
2                                                  1             
3                                                  0             
4                                                  1             

   How does the lack of financial aid affect your academic performance?  \
0                                                  2                      
1                                                  2                      
2                                                  0                      
3                                                  2                      
4                                                  1                      

   Chronic_Illness  Sleep Duration(hours)  Sleep Quality  Financial Stress  \
0                0                      3              2                 0   
1                0                      3              2                 1   
2                1                      3              0                 0   
3                0                      3              0                 0   
4                0                      6              1                 1   

   Have you ever had suicidal thoughts ?  Overall Student mental Health  
0                                      0                              1  
1                                      0                              0  
2                                      0                              2  
3                                      0                              2  
4                                      1                              2

In [ ]:
X=df.drop('Overall Student mental Health',axis=1)

In [ ]:
X

Gender  Age  City  CGPA  Program  Residence Type  Academic Pressure  \
0          1    1     4    71        5               1                  2   
1          0    1     4    23        5               1                  0   
2          1    0     3    57        1               1                  1   
3          0    0     5    24        3               1                  0   
4          0    1     6    49        5               2                  0   
...      ...  ...   ...   ...      ...             ...                ...   
1053       0    2    10    60       14               2                  0   
1054       1    3     6    82       21               1                  0   
1055       0    2     0    82        3               1                  1   
1056       1    3    11    71       10               1                  0   
1057       0    3     2    82       22               2                  0   

      Does the end of the semester affect sense of the academic pressure?  \
0                                                     0                     
1                                                     0                     
2                                                     1                     
3                                                     0                     
4                                                     1                     
...                                                 ...                     
1053                                                  0                     
1054                                                  0                     
1055                                                  0                     
1056                                                  1                     
1057                                                  0                     

      How often you feel Academic Pressure in a running semester?  \
0                                                     1             
1                                                     0             
2                                                     0             
3                                                     2             
4                                                     2             
...                                                 ...             
1053                                                  2             
1054                                                  0             
1055                                                  1             
1056                                                  2             
1057                                                  1             

      Are you satisfied with your results each semester?  \
0                                                     2    
1                                                     1    
2                                                     1    
3                                                     1    
4                                                     1    
...                                                 ...    
1053                                                  2    
1054                                                  2    
1055                                                  2    
1056                                                  2    
1057                                                  2    

      How much academic help do you get from your friends?  \
0                                                     0      
1                                                     1      
2                                                     2      
3                                                     2      
4                                                     1      
...                                                 ...      
1053                                                  2      
1054                                                  0      
1055                                            

In [ ]:
y=df['Overall Student mental Health']

In [ ]:
y

0       1
1       0
2       2
3       2
4       2
       ..
1053    1
1054    1
1055    2
1056    2
1057    1
Name: Overall Student mental Health, Length: 1058, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25 , random_state=5)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model=LogisticRegression()

In [ ]:
model.fit(X_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
model.predict(X_test)

array([2, 0, 0, 0, 0, 2, 2, 1, 1, 1, 2, 2, 2, 1, 0, 1, 0, 0, 1, 0, 2, 2,
       1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 2, 0, 0, 1, 2, 0, 2, 2, 0,
       1, 2, 2, 1, 0, 2, 0, 1, 0, 2, 1, 2, 2, 2, 0, 1, 0, 1, 2, 1, 1, 0,
       0, 2, 1, 2, 1, 2, 0, 2, 0, 1, 2, 0, 1, 1, 2, 1, 0, 2, 1, 2, 0, 2,
       2, 1, 2, 0, 2, 2, 1, 2, 1, 2, 2, 2, 2, 0, 1, 0, 1, 0, 1, 2, 0, 1,
       2, 1, 2, 2, 2, 1, 1, 0, 0, 0, 2, 2, 1, 0, 1, 0, 2, 2, 0, 2, 1, 0,
       1, 0, 2, 2, 2, 2, 0, 2, 1, 2, 1, 0, 1, 2, 0, 2, 0, 0, 1, 0, 2, 1,
       2, 2, 2, 0, 1, 2, 2, 2, 1, 2, 2, 1, 1, 0, 1, 1, 2, 2, 1, 0, 1, 0,
       0, 2, 0, 1, 0, 2, 2, 0, 2, 1, 2, 2, 2, 0, 0, 0, 0, 2, 1, 2, 0, 0,
       1, 1, 1, 2, 0, 2, 1, 1, 2, 1, 1, 2, 0, 2, 0, 2, 1, 2, 1, 2, 1, 0,
       1, 1, 0, 1, 0, 2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 1, 1, 0, 2, 2, 1, 2,
       0, 1, 2, 2, 2, 0, 1, 2, 1, 0, 0, 1, 2, 0, 0, 2, 2, 2, 2, 2, 2, 1,
       0])

In [ ]:
model.score(X_test,y_test)

0.8075471698113208

In [ ]:
pred=model.predict(X_test)

In [ ]:
pred

array([2, 0, 0, 0, 0, 2, 2, 1, 1, 1, 2, 2, 2, 1, 0, 1, 0, 0, 1, 0, 2, 2,
       1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 2, 0, 0, 1, 2, 0, 2, 2, 0,
       1, 2, 2, 1, 0, 2, 0, 1, 0, 2, 1, 2, 2, 2, 0, 1, 0, 1, 2, 1, 1, 0,
       0, 2, 1, 2, 1, 2, 0, 2, 0, 1, 2, 0, 1, 1, 2, 1, 0, 2, 1, 2, 0, 2,
       2, 1, 2, 0, 2, 2, 1, 2, 1, 2, 2, 2, 2, 0, 1, 0, 1, 0, 1, 2, 0, 1,
       2, 1, 2, 2, 2, 1, 1, 0, 0, 0, 2, 2, 1, 0, 1, 0, 2, 2, 0, 2, 1, 0,
       1, 0, 2, 2, 2, 2, 0, 2, 1, 2, 1, 0, 1, 2, 0, 2, 0, 0, 1, 0, 2, 1,
       2, 2, 2, 0, 1, 2, 2, 2, 1, 2, 2, 1, 1, 0, 1, 1, 2, 2, 1, 0, 1, 0,
       0, 2, 0, 1, 0, 2, 2, 0, 2, 1, 2, 2, 2, 0, 0, 0, 0, 2, 1, 2, 0, 0,
       1, 1, 1, 2, 0, 2, 1, 1, 2, 1, 1, 2, 0, 2, 0, 2, 1, 2, 1, 2, 1, 0,
       1, 1, 0, 1, 0, 2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 1, 1, 0, 2, 2, 1, 2,
       0, 1, 2, 2, 2, 0, 1, 2, 1, 0, 0, 1, 2, 0, 0, 2, 2, 2, 2, 2, 2, 1,
       0])

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,pred)

array([[68,  1, 10],
       [ 0, 69, 22],
       [ 5, 13, 77]])

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.93      0.86      0.89        79
           1       0.83      0.76      0.79        91
           2       0.71      0.81      0.75        95

    accuracy                           0.81       265
   macro avg       0.82      0.81      0.81       265
weighted avg       0.82      0.81      0.81       265



In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
clf=DecisionTreeClassifier()

In [ ]:
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
clf.predict(X_test)

array([2, 0, 0, 0, 0, 2, 2, 1, 2, 1, 1, 2, 1, 1, 0, 1, 0, 0, 2, 2, 2, 0,
       1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 2, 0, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 2, 1, 0, 2, 0, 1, 2, 2, 1, 2, 2, 2, 0, 1, 0, 1, 2, 1, 1, 0,
       0, 2, 1, 2, 1, 2, 0, 2, 0, 1, 2, 0, 1, 1, 1, 2, 0, 1, 1, 1, 0, 2,
       1, 2, 2, 0, 1, 1, 1, 1, 1, 2, 1, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1,
       2, 1, 1, 1, 2, 2, 1, 0, 0, 0, 2, 2, 1, 0, 1, 0, 2, 0, 0, 2, 2, 0,
       2, 0, 2, 2, 1, 2, 0, 2, 2, 1, 1, 0, 2, 2, 0, 1, 0, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 0, 1, 1, 2, 1, 1, 0, 1, 0,
       0, 1, 0, 2, 0, 2, 2, 0, 2, 1, 2, 2, 2, 0, 0, 0, 0, 2, 1, 2, 0, 2,
       1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 1, 0, 2, 2, 0, 1, 1, 2, 1, 2, 1, 0,
       1, 1, 0, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 2, 1, 1, 0, 1, 2, 1, 0,
       0, 1, 2, 2, 2, 0, 1, 0, 2, 0, 0, 1, 2, 0, 0, 2, 2, 1, 2, 0, 2, 1,
       0])

In [ ]:
clf.score(X_test,y_test)

0.969811320754717

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
Rclf=RandomForestClassifier()

In [ ]:
Rclf.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
Rclf.predict(X_test)

array([2, 0, 0, 0, 0, 2, 2, 1, 2, 1, 1, 2, 1, 1, 0, 1, 0, 0, 2, 2, 2, 2,
       1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 2, 0, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 2, 1, 0, 2, 0, 1, 2, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 1, 1, 0,
       0, 2, 1, 2, 1, 2, 0, 2, 0, 1, 2, 0, 1, 1, 1, 2, 0, 1, 1, 1, 0, 2,
       1, 2, 2, 0, 1, 1, 1, 1, 1, 2, 1, 2, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1,
       2, 1, 1, 1, 2, 1, 1, 0, 0, 0, 2, 2, 1, 0, 1, 0, 2, 0, 0, 2, 2, 0,
       2, 0, 2, 2, 1, 2, 0, 2, 2, 1, 1, 0, 2, 2, 0, 1, 0, 0, 1, 0, 0, 1,
       2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 0, 1, 1, 2, 1, 1, 0, 1, 0,
       0, 1, 0, 2, 0, 2, 2, 0, 2, 1, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2,
       1, 1, 1, 2, 0, 2, 1, 1, 2, 1, 1, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 0,
       1, 1, 0, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 2, 1, 1, 0, 1, 2, 1, 0,
       0, 1, 2, 2, 2, 0, 1, 0, 2, 0, 0, 1, 2, 0, 0, 2, 2, 1, 2, 0, 2, 1,
       0])

In [ ]:
Rclf.score(X_test,y_test)

0.9849056603773585

In [ ]:
from sklearn.svm import SVC

In [ ]:
svc_classifier = SVC()

In [ ]:
svc_classifier.fit(X_train,y_train)

SVC()

In [ ]:
svc_classifier.predict(X_test)

array([2, 0, 2, 0, 0, 2, 2, 1, 2, 2, 1, 0, 2, 1, 0, 1, 0, 0, 1, 0, 2, 0,
       2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 0, 0, 0, 2, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 0, 2, 2, 1, 0, 1, 2, 2, 0, 1, 0, 0, 2, 1, 0, 1, 2, 0,
       0, 2, 2, 1, 1, 0, 0, 2, 0, 2, 0, 0, 1, 2, 2, 1, 0, 2, 1, 1, 0, 0,
       2, 1, 1, 0, 2, 2, 2, 1, 1, 0, 2, 2, 2, 0, 1, 0, 1, 0, 1, 0, 2, 1,
       1, 0, 2, 2, 0, 1, 1, 0, 2, 0, 0, 1, 1, 0, 2, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 2, 1, 2, 0, 0, 1, 1, 2, 2, 0, 2, 1, 0, 1, 0, 0, 2, 0, 2, 1,
       2, 1, 2, 0, 2, 1, 1, 2, 1, 0, 2, 2, 1, 0, 2, 2, 2, 1, 2, 0, 1, 2,
       0, 2, 0, 1, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0,
       1, 1, 2, 1, 0, 0, 1, 1, 1, 2, 1, 0, 0, 1, 0, 1, 2, 2, 1, 0, 2, 0,
       1, 1, 0, 1, 0, 2, 0, 0, 0, 2, 1, 1, 2, 1, 1, 2, 2, 0, 2, 1, 1, 2,
       0, 0, 2, 0, 1, 0, 1, 0, 2, 0, 0, 2, 2, 0, 0, 1, 1, 2, 1, 2, 0, 2,
       0])

In [ ]:
svc_classifier.score(X_test,y_test)

0.5056603773584906

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3)

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
knn.predict(X_test)

array([2, 0, 0, 2, 0, 2, 2, 1, 2, 1, 1, 2, 1, 1, 0, 1, 2, 0, 1, 2, 1, 0,
       1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 0, 0, 0, 1, 2, 0, 0, 2, 0,
       1, 2, 1, 1, 0, 2, 2, 1, 0, 2, 1, 2, 2, 2, 0, 0, 2, 1, 2, 1, 2, 0,
       0, 2, 1, 2, 1, 0, 0, 2, 0, 2, 2, 0, 2, 1, 1, 1, 0, 1, 1, 2, 0, 2,
       2, 2, 2, 0, 1, 1, 2, 1, 1, 0, 1, 2, 0, 0, 2, 0, 1, 2, 1, 2, 0, 1,
       1, 2, 0, 1, 0, 1, 1, 0, 1, 0, 0, 2, 1, 0, 1, 0, 1, 2, 2, 2, 1, 0,
       2, 0, 2, 1, 1, 2, 0, 2, 1, 1, 1, 0, 2, 2, 0, 1, 2, 0, 1, 0, 0, 1,
       2, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 0, 1, 1, 2, 1, 1, 0, 1, 0,
       0, 2, 2, 1, 0, 1, 2, 0, 2, 1, 2, 1, 2, 0, 0, 0, 0, 2, 1, 0, 0, 2,
       1, 1, 1, 1, 0, 2, 1, 1, 1, 1, 1, 0, 2, 2, 0, 1, 1, 2, 1, 2, 1, 0,
       1, 1, 0, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 2, 1, 1, 0, 1, 2, 1, 0,
       2, 2, 2, 2, 1, 0, 2, 0, 2, 0, 0, 1, 1, 0, 0, 2, 2, 1, 2, 0, 2, 1,
       0])

In [ ]:
knn.score(X_test,y_test)

0.7811320754716982

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
GNB=GaussianNB()

In [ ]:
GNB.fit(X_train,y_train)

GaussianNB()

In [ ]:
GNB.predict(X_test)

array([2, 0, 0, 0, 0, 2, 2, 1, 1, 1, 1, 2, 2, 1, 0, 1, 0, 0, 1, 0, 2, 2,
       1, 1, 2, 1, 2, 2, 0, 1, 1, 2, 1, 1, 1, 2, 0, 0, 1, 2, 0, 2, 2, 0,
       1, 2, 2, 1, 0, 2, 2, 1, 0, 2, 1, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1, 0,
       0, 0, 1, 2, 1, 2, 0, 2, 0, 1, 2, 0, 2, 1, 2, 1, 0, 2, 1, 2, 0, 2,
       2, 2, 2, 0, 1, 1, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 0, 1, 2, 0, 1,
       2, 1, 2, 0, 2, 1, 1, 0, 2, 0, 0, 2, 1, 0, 1, 0, 2, 0, 0, 2, 1, 0,
       1, 0, 2, 2, 1, 2, 0, 2, 1, 1, 1, 0, 1, 2, 0, 2, 0, 0, 1, 0, 2, 1,
       1, 2, 0, 0, 1, 2, 1, 2, 1, 0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 0,
       0, 2, 0, 1, 0, 1, 2, 0, 2, 1, 2, 2, 2, 0, 0, 2, 0, 0, 1, 2, 0, 0,
       1, 1, 1, 2, 0, 2, 1, 1, 1, 1, 1, 0, 0, 2, 0, 2, 1, 1, 1, 2, 1, 0,
       1, 1, 0, 1, 0, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 1, 1, 0, 1, 2, 1, 2,
       0, 1, 0, 2, 2, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 2, 1, 2, 2, 2, 1,
       0])

In [ ]:
GNB.score(X_test,y_test)

0.7660377358490567